### ISSUE TITLE
Thanks for your work

### ISSUE THREAD

**Issue by FlyGoat** [esno/yoga-bios-unlock#11]
Actually I published a version myself for Linux.

https://gist.github.com/FlyGoat/5f0dba5b5ccc1b6ab73023489e1e989a

But really appreciate that we have a much more elegant C version :-)

**Comment by sarvasana** [comment]
In just 5 lines of python?

**Comment by esno** [comment]
the whole magic happens within those for lines. the rest is DMI checking to ensure it's only executed on proper hardware
