### ISSUE TITLE
Will this work on other Lenovo computers?

### ISSUE THREAD

**Issue by korikori** [esno/yoga-bios-unlock#13]
I understand that this is probably not the right place for such a question, but:
1) do you believe that this can be performed on a similar device such as the Ideapad 5 14are05?
2) how would one go about doing so?
Thanks!

**Comment by FlyGoat** [comment]
No, only a small number of Lenovo devices have such backdoor-ish method to turn on the hidden menu.
You mey reverse-engineering BIOS to find that out.

**Comment by korikori** [comment]
Thanks for reaching out!
