### ISSUE TITLE
Bios rollback

### ISSUE THREAD

**Issue by benoe77** [esno/yoga-bios-unlock#18]
Hi, do you think it is safe to roll back the bios to an earlier version?
From warranty service I got back the notebook with bios version 38. I want to go back to 32.

**Comment by esno** [comment]
Hi, I know few people downgraded their bios to a lower version. It should be safe to do so: see [this comment](https://www.reddit.com/r/AMDLaptops/comments/jvj4or/comment/gd9esqw/?utm_source=share&utm_medium=web2x&context=3) for reference
