### ISSUE TITLE
is there any update on DMCN39WW?

### ISSUE THREAD

**Issue by suleymankalkan** [esno/yoga-bios-unlock#19]
This version is published at 29 Sept. I will try to unlock it for disable S3 deep to solve sleep problem on linux. Should i try? or is there any files/instructions for downgrading bios version? I couldnt see it on lenovo support page.

**Comment by suleymankalkan** [comment]
Thank you! So i downgraded the bios to version DMCN38WW and tried to unlock it with the instructions given. I get a board_version does not match error with the file. How should i proceed? 


`❯ ./yoga-bios-unlock --read
Run in read mode
Be aware that readmode temporarily changes value of port 0x72 to index 0xf7
board_version does not match (SDK0J40688 WIN  )
Wrong device, aborting!
`

**Comment by suleymankalkan** [comment]
I tried with --force and it worked, will post pictures of bios menus soon to this issue. I also want to make a little contribution for including my board to the repo. If thats ok with you.

Thanks again.

**Comment by esno** [comment]
you're welcome.
>  also want to make a little contribution for including my board to the repo. If thats ok with you.
Feel free to do so :)

I'll keep that issue open for a while. Maybe someone verifies if DMCN39WW works as well

**Comment by DJPorv** [comment]
I can confirm that `--force` on DMCN39WW works.  
Thanks @esno, was going crazy not being able to suspend.

**Comment by esno** [comment]
thank you for confirmation and nice to hear that this tool brings a benefit to people :)
