### ISSUE TITLE
BIOS version DMCN36WW

### ISSUE THREAD

**Issue by dot-pulsar** [esno/yoga-bios-unlock#2]
Is it possible to use this method for bios version DMCN36WW ?

**Comment by esno** [comment]
I don't know anything about `DMCN36WW` - sorry. That's the reason why this tool checks BIOS versions and only whitelists  versions that are verified.

Since `DMCN34WW` already hides some menues like XFR enhancements it may make more sense to rollback to `DMCN32WW` than using newer versions.

I'll keep this issue open for the moment to give people the chance to confirm it's working and later on adapting the `is_yoga()` function.

**Comment by toszlanyi** [comment]
Hey Matthias, I just received the exact same notebook just with a newer BIOS v36 as mentioned before. Is there any way I could "safely" test if the unlocking works? With spending that much money I would not like to brake my new Yoga immediately. But I have no issues to test and dig deeper. Maybe a good way is to read my current BIOS and compare with the v32 dump you may still have to get some kind of confidence before start. I am on Linux only. Win is completely erased from my notebook ;) 

```
$ sudo dmidecode -t bios -q

BIOS Information
        Vendor: LENOVO
        Version: DMCN36WW
        Release Date: 11/18/2020
        Address: 0xE0000
        Runtime Size: 128 kB
        ROM Size: 16 MB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                BIOS shadowing is allowed
                Boot from CD is supported
                Selectable boot is supported
                EDD is supported
                Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)
                Japanese floppy for Toshiba 1.2 MB is supported (int 13h)
                5.25"/360 kB floppy services are supported (int 13h)
                5.25"/1.2 MB floppy services are supported (int 13h)
                3.5"/720 kB floppy services are supported (int 13h)
                3.5"/2.88 MB floppy services are supported (int 13h)
                8042 keyboard services are supported (int 9h)
                CGA/mono video services are supported (int 10h)
                ACPI is supported
                USB legacy is supported
                BIOS boot specification is supported
                Targeted content distribution is supported
                UEFI is supported
        BIOS Revision: 1.36
        Firmware Revision: 1.28

BIOS Language Information
        Language Description Format: Long
        Installable Languages: 4
                en|US|iso8859-1
                fr|FR|iso8859-1
                ja|JP|unicode
                zh|TW|unicode
        Currently Installed Language: en|US|iso8859-1
```
Cheers!
Tobias  /  "OsZ"

**Comment by MrDiba** [comment]
I have edited the .c file (added a define for the version 36 and added a line to dmi_strings_t) and can confirm that the unlock works.
