### ISSUE TITLE
Compatibility with other lenovo boards 

### ISSUE THREAD

**Issue by jcnwholland** [esno/yoga-bios-unlock#23]
I ran the file and it ate my cat, and burned my house down :-)

No, the reason i'm making this ticket is if i can peruse you to take a look at the lenovo z490 based mainboard, where they have locked features as xmp in the advanced section.. Making installed custom ram running at 50%.. while xmp is on the board..

thxn

Latest bios version: https://download.lenovo.com/pccbbs/deskt...y12usa.exe
Files after extraction: https://www.dropbox.com/t/tsU5NUkumVdxDwJa

**Comment by esno** [comment]
Hi, sorry I made a tool out of FlyGoats guide to unlock BIOS features for my yoga slim 7.
I can't help you here and even I would have time for that I can't provide untested code to the world since I don't have the hardware to verify anything.
