### ISSUE TITLE
Advanced BIOS?

### ISSUE THREAD

**Issue by benoe77** [esno/yoga-bios-unlock#25]
I read about a method [here](https://www.reddit.com/r/linuxhardware/comments/i28nm5/comment/hjkpisu/?utm_source=share&utm_medium=web2x&context=3) and [here](https://forums.lenovo.com/topic/findpost/1092/5018261/5262868) to achieve bios unlock that should work with other models of Lenovo notebooks. I'm yet to try it out on my Yoga Slim 7 14ARE05 but it is here for anyone who is brave enough to try it:

"1. Turn off OneKeyBattery mode in BIOS setup (this won't work with it enabled), save settings, power off
2. Type, with the laptop powered off: F1 1 Q A Z F2 2 W S X F3 3 E D C F4 4 R F V F5 5 T G B F6 6 Y H N. If you notice the pattern, it's just going down the column from F1 to the letter in the last keyboard row, from F1 to F6.
3. Boot the laptop with F2 pressed to get into BIOS as usual, you'll get into the BIOS but with a few options more unlocked."

**Comment by benoe77** [comment]
Nah, it doesn't seem to work :(

**Comment by esno** [comment]
since you pointed out that this is not working, I'll close that issue for now.
regards crito
