### ISSUE TITLE
Why function read_pin doesn't set the original value back to 0x72?

### ISSUE THREAD

**Issue by Arisa-Snowbell** [esno/yoga-bios-unlock#26]
The title is self explanatory, 
I have absolutely zero knowledge about accessing Extend CMOS Index/Data Port but I am guessing(From my basic understanding) it would be better to save the original value aka index port position and after reading 0x73 set the index port back to the original?
so if other software that accesses the 0x73 and doesn't make sure it accesses correct index port doesn't end up messing something up?

**Comment by esno** [comment]
the index port is not set in any function neither lock, unlock nor read.
it's set upfront (see https://github.com/esno/yoga-bios-unlock/blob/master/src/yoga-bios-unlock.c#L218) and will be reset at the end of execution (see https://github.com/esno/yoga-bios-unlock/blob/master/src/yoga-bios-unlock.c#L233).

only reason for moving read, lock and unlock into own functions was to keep the switch case block lean and provide readability on which mode is reserved for what purpose.

From my understanding software should never access a data port without verifying the value of the index port.

**Comment by Arisa-Snowbell** [comment]
Oh, I missed that, I apologize,
Thank you for explaining it
Closing

**Comment by esno** [comment]
you're welcome
