### ISSUE TITLE
Yoga Slim 7 ProX 14ARH7 Support

### ISSUE THREAD

**Issue by dylangerdaly** [esno/yoga-bios-unlock#29]
Hello,

I'm trying to unlock the UEFI on my Slim 7 ProX, as there appears to be some issues running Xen, this could be related to some weird Microsoft thing Lenovo have enabled.

I have UEFITool working with a InsydeH20 .fd from here: [https://pcsupport.lenovo.com/ch/en/products/laptops-and-netbooks/yoga-series/yoga-slim-7-prox-14arh7/downloads/driver-list/component?name=BIOS%2FUEFI](https://pcsupport.lenovo.com/ch/en/products/laptops-and-netbooks/yoga-series/yoga-slim-7-prox-14arh7/downloads/driver-list/component?name=BIOS%2FUEFI)

Is it possible to unlock more UEFI options for this laptop?

Cheers

**Comment by esno** [comment]
Hey,

sorry I don't own this device so I can't say much about it.
At least the bios naming is different to other versions of yoga slim I saw before
so I would't expect to get it working out of the box.

If you find a way to unlock it. feel free to open a pull request or a new ticket providing me further notes about it.
