### ISSUE TITLE
How to lock BIOS back

### ISSUE THREAD

**Issue by dot-pulsar** [esno/yoga-bios-unlock#3]
I want to take my laptop to a service center. And if they see an unlocked BIOS, then the guarantee could be lost. How can you believe him in his original state?

**Comment by sarvasana** [comment]
You can flash the bios. Depending on the bios settings you can or cannot downgrade it.

**Comment by dot-pulsar** [comment]
I used BIOS version DMCN32WW (unloked), then I updated to version DMCN38WW. But the unlocking was not lost. I can't figure out how to reset it back.

**Comment by esno** [comment]
Hi, did you run this tool in *readmode* before unlocking and if so do you still have the `stdout` for that?
I will test locking as soon as I'm next to my notebook.

Meanwhile Did you check differences in version *DMCN32WW* and *DMCN38WW*? I would be interested to see which menues are still available. If you figured out any differences could you please create a new issue mentioning such differences to add them into README? Thanks in advance.

**Comment by esno** [comment]
implemented in 378091fc78f31a0cf0f357554f5a52003eb36346
