### ISSUE TITLE
Advanced menu without unlock?

### ISSUE THREAD

**Issue by benoe77** [esno/yoga-bios-unlock#31]
Look what I found:

https://github.com/DavidS95/Smokeless_UMAF

altough I haven't tried yet.

**Comment by esno** [comment]
Hey,

I don't see source code or a license file here.
The reason why I wrote this tool was not to rely on closed source tools in any way of my life.
In that case I will not have a deeper look onto it nor test it out.

But thanks for mentioning. Maybe others will find it useful

**Comment by xlarin** [comment]
> 

I checked - it works! Even on the latest firmware DMCN43WW.
I turned on S3 mode.
