### ISSUE TITLE
"board version does not match" but it does

### ISSUE THREAD

**Issue by Janybanny** [esno/yoga-bios-unlock#34]
When I run the command `./yoga-bios-unlock --unlock` I get:
```
Run in unlock mode
board version does not match
Wrong device, aborting!
```
`cat /sys/class/dmi/id/board_version` returns `SDK0J40709 WIN`
`cat /sys/class/dmi/id/bios_version` returns `DMCN27WW`

So everything is supported and it should work (This is also the data that shows in the bios), but the check apparently fails. I've seen in other bug reports that the result that I get usually includes the detected board version, but mine for some reason doesn't, so I assume that it failed to get the value.

I don't exactly know how the program works, but would it make sense to set those values manually and then run the program with those manual values? And if yes, how would I go about doing this?

**Comment by esno** [comment]
hi, can you run

    echo "$(cat /sys/class/dmi/id/board_version)#"
    
to see if there are any whitespaces on your site? All boards I know returned with string

    "SDK0J40709 WIN  "

**Comment by Janybanny** [comment]
This returns
```SDK0J40709 WIN  #```
Should be fine as well

**Comment by esno** [comment]
that's weird. need to check that this evening. meanwhile you can try using `--force` to unlock

**Comment by esno** [comment]
@Janybanny can you try the [memsetfix](https://github.com/esno/yoga-bios-unlock/tree/memsetfix) branch on your board to see if your issue is related to that?
simply run

    ./yoga-bios-unlock --read
    
no need to lock and unlock again

**Comment by Janybanny** [comment]
It works now and the output is:
```
Run in read mode
Be aware that readmode temporarily changes value of port 0x72 to index 0xf7
WARNING: use at your own risk!
Agree? (y/n) y
Port 0x72 is 0xf4 and will be set to 0xf7
Port 0x73 is 0x77
```
Thanks a lot! If you still need help with testing other scenarios or something, let me know

**Comment by esno** [comment]
great thank you for retesting :)
I guess that's it. didn't find other stuff right now
