### ISSUE TITLE
Fails on DMCN34WW

### ISSUE THREAD

**Issue by rradar** [esno/yoga-bios-unlock#4]
hey @esno thank's for this great tool!

When running `./yoga-bios-unlock --read` I get this output here (same when running with sudo)
```
Run in read-mode
Be aware that readmode temporarily changes value of port 0x72 to index 0xf7
board_version does not match (SDK0J40709 WIN   ��������������������������������)
Wrong device, aborting!
```

This are my specs:
```
BIOS Information
        Vendor: LENOVO
        Version: DMCN34WW
        Release Date: 08/17/2020
System Information
        Manufacturer: LENOVO
        Product Name: 82A2
        Version: Yoga Slim 7 14ARE05
```

**Comment by esno** [comment]
Hi,
that's a strange behavior.
Could you please run
```
echo "'$(cat /sys/class/dmi/id/board_version)'"
```
I'm filling buffer with zeros first and than `strcpy()` contents of the above mentioned file

**Comment by rradar** [comment]
> echo "'$(cat /sys/class/dmi/id/board_version)'"

outputs:

`'SDK0J40709 WIN   ��������������������������������'`

**Comment by esno** [comment]
thx. what the...
Can you tell me anything about your region? This is either a bug in localization or this BIOS version has a bug in it's DMI code.

Which locales are you using?

**Comment by rradar** [comment]
> This is either a bug in localization or this BIOS version has a bug in it's DMI code.
> 
> What locales are you using?

I'm running Linux Mint 20 (*buntu base 20.04.1) with a 5.8.0 kernel. Language is english US region & timezone are portuguese

**Comment by esno** [comment]
thx for providing all the information.
I'll dig into it and see what's wrong.
Could you please copy the output of `locale` just to make sure we're using the same?

**Comment by rradar** [comment]
> Could you please copy the output of `locale` just to make sure we're using the same?

Here we go:
```LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pt_PT.UTF-8
LC_TIME=pt_PT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_PT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_PT.UTF-8
LC_NAME=pt_PT.UTF-8
LC_ADDRESS=pt_PT.UTF-8
LC_TELEPHONE=pt_PT.UTF-8
LC_MEASUREMENT=pt_PT.UTF-8
LC_IDENTIFICATION=pt_PT.UTF-8
LC_ALL=
```
the last line is unset - it looks like :thinking:

**Comment by esno** [comment]
Sorry I can't reproduce this behavior on mine. Could you please check if you get the same weird string from
```
echo "'$(cat /sys/class/dmi/id/board_version)'"
```
on a live usb stick like ubuntu directly?

**Comment by rradar** [comment]
> on a live usb stick like ubuntu directly?

I will try this. And when it works (not returning gibberish) I could then directly unlock the bios while running the live system without any "downsides" - correct?

**Comment by esno** [comment]
the distro is unrelated to the unlock mechanism. I don't see any downsides there.
If even the ubuntu live iso returns gibberish then the last option to you would be to delete this lines
https://github.com/esno/yoga-bios-unlock/blob/master/src/yoga-bios-unlock.c#L75-L76 run `make clean; make` and unlock it without `board_version` checking. But be aware that I introduced all these DMI checks to ensure it will be only invoked on a proper hardware.

**Comment by rradar** [comment]
So I'm back from my live ride and the result was the same.

But most interestingly actually was the "Lenovo Setup Utility" right after start up:

![image](https://user-images.githubusercontent.com/34582688/108125615-99106980-70a0-11eb-83df-43adffdee462.png)

**Comment by esno** [comment]
OK thats awkward. Then this is an issue with your BIOS version. But I know that people already unlocked a DMCN34WW without mentioning such issue.
I think you have two options:
Either downgrading to DMCN32WW and hope that the `board_version` string looks better which I would prefer because DMCN34WW already hides some menues you might interested in or dropping the `board_version` check like I mentioned on my previous comment.

Sorry that there's nothing else I can provide to you

**Comment by rradar** [comment]
long story short: downgrade to DMCN32WW makes the gibberish in the bios gone and unlocking works perfectly fine!

Thank's @esno for all your efforts and sharing it with community :+1:
