### ISSUE TITLE
Can't set I/O privilege level (Operation not permitted)

### ISSUE THREAD

**Issue by benoe77** [esno/yoga-bios-unlock#7]
Hi, I got this error message under ubuntu 20.04. It is my hw or some sw incompatibility?

`sudo ./yoga-bios-unlock --read
Run in read-mode
Be aware that readmode temporarily changes value of port 0x72 to index 0xf7
WARNING: use at your own risk!
Agree? (y/n) y
Can't set I/O privilege level (Operation not permitted)
`

**Comment by esno** [comment]
I added a note about that issue in readme as well as in stderr (see 785bfcbd19ea7cae6316554dc34c7869a0d64cde). thanks for figuring out and sharing your knowledge in https://github.com/esno/yoga-bios-unlock/issues/8#issuecomment-817707566
